[repository]
repo_url = 'https://github.com/encode/django-rest-framework.git'
repo_branch = 'main'
original_link = 'https://github.com/encode/django-rest-framework/tree/main/docs'
paths = [
    ['docs/api-guide/', '.reference/api-guide/'],
    ['docs/tutorial/', '.reference/tutorial/'],
    ['docs/coreapi/', '.reference/tutorial/'],
    ['docs/topics/', '.reference/topics/'],
    ['docs/index.md', '.reference/README.md'],
]
cache_file = '.files_cache.json'
